
import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vijay sai nag
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl4 = new javax.swing.JLabel();
        jl7 = new javax.swing.JLabel();
        jl10 = new javax.swing.JLabel();
        jl13 = new javax.swing.JLabel();
        jl16 = new javax.swing.JLabel();
        jl19 = new javax.swing.JLabel();
        jl22 = new javax.swing.JLabel();
        jl25 = new javax.swing.JLabel();
        jl28 = new javax.swing.JLabel();
        jl5 = new javax.swing.JLabel();
        jl8 = new javax.swing.JLabel();
        jl11 = new javax.swing.JLabel();
        jl14 = new javax.swing.JLabel();
        jl17 = new javax.swing.JLabel();
        jl20 = new javax.swing.JLabel();
        jl23 = new javax.swing.JLabel();
        jl26 = new javax.swing.JLabel();
        jl29 = new javax.swing.JLabel();
        jl6 = new javax.swing.JLabel();
        jl9 = new javax.swing.JLabel();
        jl12 = new javax.swing.JLabel();
        jl15 = new javax.swing.JLabel();
        jl18 = new javax.swing.JLabel();
        jl21 = new javax.swing.JLabel();
        jl24 = new javax.swing.JLabel();
        jl27 = new javax.swing.JLabel();
        jl30 = new javax.swing.JLabel();
        jl31 = new javax.swing.JLabel();
        jl32 = new javax.swing.JLabel();
        jl33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl34 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL45 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jl1.setBackground(new java.awt.Color(255, 255, 255));
        jl1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl1.setText("jLabel4");
        jl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl2.setText("jLabel5");
        jl2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl3.setText("jLabel6");
        jl3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl4.setBackground(new java.awt.Color(255, 255, 255));
        jl4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl4.setText("jLabel4");
        jl4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl7.setBackground(new java.awt.Color(255, 255, 255));
        jl7.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl7.setText("jLabel5");
        jl7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl10.setBackground(new java.awt.Color(255, 255, 255));
        jl10.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl10.setText("jLabel6");
        jl10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl13.setBackground(new java.awt.Color(255, 255, 255));
        jl13.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl13.setText("jLabel7");
        jl13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl16.setBackground(new java.awt.Color(255, 255, 255));
        jl16.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl16.setText("jLabel8");
        jl16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl19.setBackground(new java.awt.Color(255, 255, 255));
        jl19.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl19.setText("jLabel9");
        jl19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl22.setBackground(new java.awt.Color(255, 255, 255));
        jl22.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl22.setText("jLabel10");
        jl22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl25.setBackground(new java.awt.Color(255, 255, 255));
        jl25.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl25.setText("jLabel11");
        jl25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl28.setBackground(new java.awt.Color(255, 255, 255));
        jl28.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl28.setText("jLabel12");
        jl28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl5.setText("jLabel13");
        jl5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl8.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl8.setText("jLabel14");
        jl8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl11.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl11.setText("jLabel15");
        jl11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl14.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl14.setText("jLabel16");
        jl14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl17.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl17.setText("jLabel17");
        jl17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl20.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl20.setText("jLabel18");
        jl20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl23.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl23.setText("jLabel19");
        jl23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl26.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl26.setText("jLabel20");
        jl26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl29.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl29.setText("jLabel21");
        jl29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl6.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl6.setText("jLabel22");
        jl6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl9.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl9.setText("jLabel23");
        jl9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl12.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl12.setText("jLabel24");
        jl12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl15.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl15.setText("jLabel25");
        jl15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl18.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl18.setText("jLabel26");
        jl18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl21.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl21.setText("jLabel27");
        jl21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl24.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl24.setText("jLabel28");
        jl24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl27.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl27.setText("jLabel29");
        jl27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jl27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl30.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl30.setText("jLabel21");
        jl30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl31.setBackground(new java.awt.Color(255, 255, 255));
        jl31.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl31.setText("jLabel12");
        jl31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl32.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl32.setText("jLabel21");
        jl32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl33.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jl33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl33.setText("jLabel21");
        jl33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl25, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(jl22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jl13, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl29, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jl26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl33, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(jl27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jl6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jl9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jl30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STU ID");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Name");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("STATUS");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));

        jl34.setBackground(new java.awt.Color(0, 51, 51));
        jl34.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jl34.setForeground(new java.awt.Color(255, 255, 255));
        jl34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 3, true));

        jL7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jL45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL45, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl34, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(879, 879, 879)
                .addComponent(jL7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jL45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Designed by");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VIJAY SAI NAG D");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AP18110010302");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Submit Attendence");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        jButton3.setText("View Attendence");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(220, 220, 220)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String dt=jl34.getText();
        
        String num1=jl1.getText();
        String name1=jl2.getText();
        String stat1=jl3.getText();
        
         String num2=jl4.getText();
        String name2=jl5.getText();
        String stat2=jl6.getText();
        
          try{
        
       
            java.sql.Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/logs","vijay", "3103");
            java.sql.PreparedStatement st = conn.prepareStatement("insert into reg(date,id,name,status)values(?,?,?,?)");
            st.setString(1, dt);
            st.setString(2, num1);
            st.setString(3, name1);
            st.setString(4, stat1);
  
            st.executeUpdate();
            
           JOptionPane.showMessageDialog(null,"SUCCESS","ENTERED DATA",JOptionPane.PLAIN_MESSAGE);
            
            
        }
        catch(SQLException ex){
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
        
    }
        try{
        
       
            java.sql.Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/logs","vijay", "3103");
            java.sql.PreparedStatement st = conn.prepareStatement("insert into reg(date,id,name,status)values(?,?,?,?)");
            st.setString(1, dt);
            st.setString(2, num2);
            st.setString(3, name2);
            st.setString(4, stat2);
            st.executeUpdate();
            
           
            
            
        }
        catch(SQLException ex){
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
        
    }
         
        
      
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        view v = new view();
        v.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JLabel jL45;
    public static javax.swing.JLabel jL7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel jl1;
    public static javax.swing.JLabel jl10;
    public static javax.swing.JLabel jl11;
    public static javax.swing.JLabel jl12;
    public static javax.swing.JLabel jl13;
    public static javax.swing.JLabel jl14;
    public static javax.swing.JLabel jl15;
    public static javax.swing.JLabel jl16;
    public static javax.swing.JLabel jl17;
    public static javax.swing.JLabel jl18;
    public static javax.swing.JLabel jl19;
    public static javax.swing.JLabel jl2;
    public static javax.swing.JLabel jl20;
    public static javax.swing.JLabel jl21;
    public static javax.swing.JLabel jl22;
    public static javax.swing.JLabel jl23;
    public static javax.swing.JLabel jl24;
    public static javax.swing.JLabel jl25;
    public static javax.swing.JLabel jl26;
    public static javax.swing.JLabel jl27;
    public static javax.swing.JLabel jl28;
    public static javax.swing.JLabel jl29;
    public static javax.swing.JLabel jl3;
    public static javax.swing.JLabel jl30;
    public static javax.swing.JLabel jl31;
    public static javax.swing.JLabel jl32;
    public static javax.swing.JLabel jl33;
    public static javax.swing.JLabel jl34;
    public static javax.swing.JLabel jl4;
    public static javax.swing.JLabel jl5;
    public static javax.swing.JLabel jl6;
    public static javax.swing.JLabel jl7;
    public static javax.swing.JLabel jl8;
    public static javax.swing.JLabel jl9;
    // End of variables declaration//GEN-END:variables
}
